export * from './mini.mjs';
// not `export *`: krill-parser.js (generated by peggy) exports its error class as SyntaxError,
// and evalScope puts every export on globalThis, which would replace the built-in SyntaxError
export { StartRules, parse, SyntaxError as MiniSyntaxError } from './krill-parser.js';
