// Capability matrix: definition, validation and the generated scoreboard.
import { readFileSync } from 'node:fs';

export const TIERS = ['browser', 'desktop', 'cli'];
export const LEVELS = ['req', 'opt', 'n/a'];
// Walls in these rows mean NexusLang as a new front end; any other row means the engine.
const FRONT_END_PREFIXES = ['ARR', 'LANG', 'TUNE'];
const PORT_TIERS = ['desktop', 'cli'];

export function validateCapabilities(caps) {
  const errors = [];
  const seen = new Set();
  for (const c of caps.capabilities ?? []) {
    if (!/^[A-Z]+-\d+$/.test(c.id)) errors.push(`bad id: ${c.id}`);
    if (seen.has(c.id)) errors.push(`duplicate id: ${c.id}`);
    seen.add(c.id);
    if (!c.criterion) errors.push(`${c.id}: missing criterion`);
    for (const tier of TIERS) {
      if (!LEVELS.includes(c.tiers?.[tier])) errors.push(`${c.id}: bad level for ${tier}: ${c.tiers?.[tier]}`);
    }
  }
  if (!seen.size) errors.push('no capabilities');
  return errors;
}

export function loadCapabilities(path) {
  const caps = JSON.parse(readFileSync(path, 'utf8'));
  const errors = validateCapabilities(caps);
  if (errors.length) throw new Error(`invalid ${path}:\n${errors.join('\n')}`);
  return caps;
}

export function cellsForTier(caps, tier) {
  return caps.capabilities
    .filter((c) => c.tiers[tier] !== 'n/a')
    .map((c) => ({ id: c.id, level: c.tiers[tier], thresholds: c.thresholds?.[tier] ?? {} }));
}

export function portReview(caps, resultsByTier) {
  const review = [];
  for (const tier of PORT_TIERS) {
    const results = resultsByTier[tier]?.results ?? {};
    for (const c of caps.capabilities) {
      const result = results[c.id];
      if (c.tiers[tier] !== 'req' || result?.status !== 'wall') continue;
      const kind = FRONT_END_PREFIXES.includes(c.id.split('-')[0]) ? 'front-end' : 'engine';
      review.push({ id: c.id, tier, kind, evidence: result.notes.evidence });
    }
  }
  return review;
}

// A result is stale when it carries provenance for thresholds that no longer match capabilities.json.
// Results with no `run` (old files, or fillMissing placeholders) are never marked.
function isStale(result, currentThresholds) {
  if (!result?.run) return false;
  return JSON.stringify(result.run.thresholds ?? {}) !== JSON.stringify(currentThresholds);
}

function formatCell(level, result, currentThresholds) {
  if (level === 'n/a') return 'n/a';
  const status = result?.status ?? 'not-run';
  const headline = result?.metrics?.headline;
  const stale = isStale(result, currentThresholds) ? ' ⚠ stale' : '';
  return `${level} · ${status}${headline ? ` (${headline})` : ''}${stale}`;
}

export function renderMatrix(caps, resultsByTier) {
  const lines = ['# Capability matrix', '', 'Generated by `tools/capabilities/run.mjs`. Do not edit by hand.', ''];
  lines.push('| Tier | Results from |', '|---|---|');
  for (const tier of TIERS) lines.push(`| ${tier} | ${resultsByTier[tier]?.date ?? 'never run'} |`);
  lines.push('', '| ID | Capability | Browser | Desktop | CLI |', '|---|---|---|---|---|');
  for (const c of caps.capabilities) {
    const cells = TIERS.map((tier) =>
      formatCell(c.tiers[tier], resultsByTier[tier]?.results?.[c.id], c.thresholds?.[tier] ?? {}),
    );
    lines.push(`| ${c.id} | ${c.name} | ${cells.join(' | ')} |`);
  }
  lines.push('', '## Port review', '');
  const review = portReview(caps, resultsByTier);
  if (!review.length) lines.push('No walls in required Desktop or CLI cells.');
  for (const r of review) lines.push(`- **${r.id}** (${r.tier}, ${r.kind}): ${r.evidence}`);
  return `${lines.join('\n')}\n`;
}
